{"uid":"d70c14f2997740c8","name":"test_given_cos_lite_integrated_with_sdcore_when_searching_for_5g_network_overview_dashboard_in_grafana_then_dashboard_exists","fullName":"tests.integration.test_integration.TestSDCoreBundle#test_given_cos_lite_integrated_with_sdcore_when_searching_for_5g_network_overview_dashboard_in_grafana_then_dashboard_exists","historyId":"3be1fd6b051e2a7f16274330c84676d8","time":{"start":1741660849832,"stop":1741660853707,"duration":3875},"status":"broken","statusMessage":"KeyError: 'url'","statusTrace":"Traceback (most recent call last):\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 341, in from_call\n    result: TResult | None = func()\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 242, in <lambda>\n    lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 92, in pytest_runtest_call\n    yield from thread_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/_pytest/threadexception.py\", line 68, in thread_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 95, in pytest_runtest_call\n    yield from unraisable_exception_runtest_hook()\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/_pytest/unraisableexception.py\", line 70, in unraisable_exception_runtest_hook\n    yield\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 846, in pytest_runtest_call\n    yield from self._runtest_for(item, \"call\")\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/_pytest/logging.py\", line 829, in _runtest_for\n    yield\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/_pytest/capture.py\", line 898, in pytest_runtest_call\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 167, in _multicall\n    teardown.throw(outcome._exception)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/_pytest/skipping.py\", line 257, in pytest_runtest_call\n    return (yield)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/_pytest/runner.py\", line 174, in pytest_runtest_call\n    item.runtest()\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 1627, in runtest\n    self.ihook.pytest_pyfunc_call(pyfuncitem=self)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pluggy/_hooks.py\", line 513, in __call__\n    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pluggy/_manager.py\", line 120, in _hookexec\n    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 182, in _multicall\n    return outcome.get_result()\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pluggy/_result.py\", line 100, in get_result\n    raise exc.with_traceback(exc.__traceback__)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pluggy/_callers.py\", line 103, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/_pytest/python.py\", line 159, in pytest_pyfunc_call\n    result = testfunction(**testargs)\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/.tox/integration/lib/python3.10/site-packages/pytest_asyncio/plugin.py\", line 529, in inner\n    _loop.run_until_complete(task)\n  File \"/usr/lib/python3.10/asyncio/base_events.py\", line 649, in run_until_complete\n    return future.result()\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/tests/integration/test_integration.py\", line 88, in test_given_cos_lite_integrated_with_sdcore_when_searching_for_5g_network_overview_dashboard_in_grafana_then_dashboard_exists\n    grafana_url, grafana_passwd = await self._get_grafana_url_and_admin_password()\n  File \"/home/ubuntu/actions-runner/_work/sdcore-tests/sdcore-tests/tests/integration/test_integration.py\", line 152, in _get_grafana_url_and_admin_password\n    return action_output[\"url\"], action_output[\"admin-password\"]\nKeyError: 'url'","flaky":false,"newFailed":false,"newBroken":true,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[{"name":"event_loop","time":{"start":1741660286043,"stop":1741660286043,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_xunit_setup_class_fixture_TestSDCoreBundle","time":{"start":1741660286043,"stop":1741660286445,"duration":402},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"abort_on_fail","time":{"start":1741660849832,"stop":1741660849832,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"afterStages":[{"name":"abort_on_fail::0","time":{"start":1741660853710,"stop":1741660853710,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"_xunit_setup_class_fixture_TestSDCoreBundle::0","time":{"start":1741660853710,"stop":1741660853710,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::2","time":{"start":1741660853711,"stop":1741660853711,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_close_event_loop","time":{"start":1741660853711,"stop":1741660853711,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false},{"name":"event_loop::_provide_clean_event_loop","time":{"start":1741660853711,"stop":1741660853711,"duration":0},"status":"passed","steps":[],"attachments":[],"parameters":[],"shouldDisplayMessage":false,"stepsCount":0,"attachmentsCount":0,"hasContent":false,"attachmentStep":false}],"labels":[{"name":"tag","value":"abort_on_fail"},{"name":"tag","value":"asyncio"},{"name":"parentSuite","value":"tests.integration"},{"name":"suite","value":"test_integration"},{"name":"subSuite","value":"TestSDCoreBundle"},{"name":"host","value":"github-runner"},{"name":"thread","value":"28651-MainThread"},{"name":"framework","value":"pytest"},{"name":"language","value":"cpython3"},{"name":"package","value":"tests.integration.test_integration"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":6,"skipped":0,"passed":14,"unknown":0,"total":20},"items":[{"uid":"1e40a04a80c9724","reportUrl":"https://canonical.github.io/sdcore-tests/2321//#testresult/1e40a04a80c9724","status":"passed","time":{"start":1741573604210,"stop":1741573606123,"duration":1913}},{"uid":"7ece2eb71c0d7c07","reportUrl":"https://canonical.github.io/sdcore-tests/2320//#testresult/7ece2eb71c0d7c07","status":"passed","time":{"start":1741487189640,"stop":1741487191637,"duration":1997}},{"uid":"f171e1458b786323","reportUrl":"https://canonical.github.io/sdcore-tests/2319//#testresult/f171e1458b786323","status":"passed","time":{"start":1741400767635,"stop":1741400770444,"duration":2809}},{"uid":"f99a5ace23a2c42d","reportUrl":"https://canonical.github.io/sdcore-tests/2318//#testresult/f99a5ace23a2c42d","status":"passed","time":{"start":1741315148238,"stop":1741315152327,"duration":4089}},{"uid":"ed15f4af4b630361","reportUrl":"https://canonical.github.io/sdcore-tests/2317//#testresult/ed15f4af4b630361","status":"passed","time":{"start":1741229835397,"stop":1741229838221,"duration":2824}},{"uid":"7154e00affa914a0","reportUrl":"https://canonical.github.io/sdcore-tests/2315//#testresult/7154e00affa914a0","status":"passed","time":{"start":1741174655787,"stop":1741174658548,"duration":2761}},{"uid":"534aeaa6c3ce3fb","reportUrl":"https://canonical.github.io/sdcore-tests/2315//#testresult/534aeaa6c3ce3fb","status":"passed","time":{"start":1741173546433,"stop":1741173549194,"duration":2761}},{"uid":"c9c57f5039196b29","reportUrl":"https://canonical.github.io/sdcore-tests/2315//#testresult/c9c57f5039196b29","status":"passed","time":{"start":1741172510397,"stop":1741172513148,"duration":2751}},{"uid":"a7416f36f73f225c","reportUrl":"https://canonical.github.io/sdcore-tests/2311//#testresult/a7416f36f73f225c","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='grafana-0.grafana-endpoints.cos-lite.svc.cluster.local', port=3000): Max retries exceeded with url: /api/search?query=5G%20Network%20Overview (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x775f04c909d0>: Failed to resolve 'grafana-0.grafana-endpoints.cos-lite.svc.cluster.local' ([Errno -3] Temporary failure in name resolution)\"))","time":{"start":1741171691817,"stop":1741171694790,"duration":2973}},{"uid":"e5e46b66f9c2288a","reportUrl":"https://canonical.github.io/sdcore-tests/2313//#testresult/e5e46b66f9c2288a","status":"broken","statusDetails":"json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)","time":{"start":1741164949137,"stop":1741164949560,"duration":423}},{"uid":"f5a2552734f15708","reportUrl":"https://canonical.github.io/sdcore-tests/2311//#testresult/f5a2552734f15708","status":"broken","statusDetails":"json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)","time":{"start":1741159986794,"stop":1741159987228,"duration":434}},{"uid":"bffd3a3c4a543d0e","reportUrl":"https://canonical.github.io/sdcore-tests/2313//#testresult/bffd3a3c4a543d0e","status":"broken","statusDetails":"json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)","time":{"start":1741142071030,"stop":1741142071457,"duration":427}},{"uid":"ff9d6280e66b906","reportUrl":"https://canonical.github.io/sdcore-tests/2311//#testresult/ff9d6280e66b906","status":"passed","time":{"start":1741072805200,"stop":1741072807928,"duration":2728}},{"uid":"aaa792c2918cf920","reportUrl":"https://canonical.github.io/sdcore-tests/2312//#testresult/aaa792c2918cf920","status":"passed","time":{"start":1741056709935,"stop":1741056713974,"duration":4039}},{"uid":"740626595b3862f6","reportUrl":"https://canonical.github.io/sdcore-tests/2311//#testresult/740626595b3862f6","status":"broken","statusDetails":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='grafana-0.grafana-endpoints.cos-lite.svc.cluster.local', port=3000): Max retries exceeded with url: /api/search?query=5G%20Network%20Overview (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7f0c647bb1c0>: Failed to resolve 'grafana-0.grafana-endpoints.cos-lite.svc.cluster.local' ([Errno -3] Temporary failure in name resolution)\"))","time":{"start":1741019743804,"stop":1741019745728,"duration":1924}},{"uid":"6d393724957b435f","reportUrl":"https://canonical.github.io/sdcore-tests/2308//#testresult/6d393724957b435f","status":"passed","time":{"start":1740969590708,"stop":1740969593368,"duration":2660}},{"uid":"7311371c15dba483","reportUrl":"https://canonical.github.io/sdcore-tests/2307//#testresult/7311371c15dba483","status":"passed","time":{"start":1740883090386,"stop":1740883100037,"duration":9651}},{"uid":"b4ed395e193b9194","reportUrl":"https://canonical.github.io/sdcore-tests/2306//#testresult/b4ed395e193b9194","status":"passed","time":{"start":1740796770249,"stop":1740796772107,"duration":1858}},{"uid":"d4cd9a26fec92707","reportUrl":"https://canonical.github.io/sdcore-tests/2305//#testresult/d4cd9a26fec92707","status":"passed","time":{"start":1740747205989,"stop":1740747207865,"duration":1876}}]},"tags":["asyncio","abort_on_fail"]},"source":"d70c14f2997740c8.json","parameterValues":[]}